catch docker compose exec error?

diff --git a/.github/workflows/sitestudio_ci.workflow.yml b/.github/workflows/sitestudio_ci.workflow.yml
--- a/.github/workflows/sitestudio_ci.workflow.yml
+++ b/.github/workflows/sitestudio_ci.workflow.yml
@@ -41,3 +41,8 @@ jobs:
       - name: Run our scripts
         run: |
           docker compose exec -T web bash ./run.sh
+          if [ $? -gt 0 ]; then
+            printf "Failure\n"
+            exit 1
+          fi
+
